### ISSUE TITLE
access token and other information appends to URL

### ISSUE THREAD

**Issue by ankuragrwl** [manfredsteyer/angular2-oauth2#10]
I am using using your library with my angular rc4 project. My Oauth 2 server is Spring Oauth 2. 

Everything works fine but access token and other information  gets appended in the redirect Uri after successful authentication.

It becomes like this :
http://localhost:3000/setup#access_token=bf7a077c-00cd-4abe-a3dc-cbf3986dec08&token_type=bearer&state=7rxsUXgchbnNU1T3A2SwmHwpmZeQCmB9EdFlotMY&expires_in=1799563032

Please help me as I have to deliver this quickly.

**Comment by MrYawe** [comment]
Same here.

**Comment by schanzen** [comment]
Hi,

this is perfectly normal bahaviour. See Oauth2 RFC https://tools.ietf.org/html/rfc6749
- M

**Comment by ankuragrwl** [comment]
Thanks I didn't notice that.

**Comment by AaronAsAChimp** [comment]
Hmm... According to [Section 3.1.2](https://tools.ietf.org/html/rfc6749#section-3.1.2):

<blockquote>
The [redirection] endpoint URI MUST NOT include a fragment component.
</blockquote>

From my perspective, the `state` parameter ([Section 4.1.1](https://tools.ietf.org/html/rfc6749#section-4.1.1)) should be used to send the route and to return to it after login. So, this is totally a valid issue. Granted, Spring Security should handle a bad URL better, but this library is also not within spec.

I was able to work around these two issues by creating a route in angular to take all the parameters and ignore them.

``` js
const routes: RouterConfig = [
    // This route scoops up the extra parameters
    { path: 'login/:auth_info', component: 'LoginPage' },
];

// [...] the add to the OAuthService

this.oauthService.redirectUri = window.location.origin + '#/login/';
```

**Comment by schanzen** [comment]
Well, if the developer using this library is violating the spec with an invalid redirect URI it is not the job of the library to check this. It is the job of the authorization server to refuse an invalid URI.
Angular is using fragment for it's routes. This concept is incompatible with OAuth2 redirect URIs. Like you said, this can be handled with a temporary state (passed as _reference_ to a route! I dont think the URI is a good CSRF canary.) on the client side, only.
Your solution should be rejected by properly implemented IdPs.
However, I think the OPs question was not related to a redurect URI with a fragment.

PS: This is also why in the example, the redirect URI is set to the index.html. And the setup is done in the toplevel component.
PPS: In any case, this should be another sign why using implicit flow is rarely a good idea even for SPAs and provides little benefit over authcode unless you have no access to server side authorization (which is unlikely).

Cheers 
Martin
