### ISSUE TITLE
onTokenReceived called twice

### ISSUE THREAD

**Issue by AaronAsAChimp** [manfredsteyer/angular2-oauth2#12]
The `onTokenReceived` option to `OAuthService.tryLogin()` is called twice when the token was only received once. It may be as simple as removing the [first call to the function](https://github.com/manfredsteyer/angular2-oauth2/blob/8c1bc9b/oauth-service.ts#L133..L135) and let it be handled in `callEventIfExists`.

**Comment by manfredsteyer** [comment]
Thx, will fix this in the next version that comes those days.
