### ISSUE TITLE
New Angular2 configuration

### ISSUE THREAD

**Issue by german-bortoli** [manfredsteyer/angular2-oauth2#18]
On readme says that we need to configure the loginUrl, redirectUri, etc (https://github.com/manfredsteyer/angular2-oauth2#top-level-component) but on new angular2 structure should be a bit different.

We should configure it on `src/app/app.module.ts` something like Angular2Ouath2.forRoot(loginUrl: ...)

**Comment by manfredsteyer** [comment]
Thx for this info. I will consider it for the next version of the lib. I think, it would also be a good idea to create the possibility to change the configuration at runtime. could be interesting if the app supports several login servers.
