### ISSUE TITLE
Broken with Angular version 2.1.0

### ISSUE THREAD

**Issue by candidature** [manfredsteyer/angular2-oauth2#19]
I tried to integrate this with angular2 (using google platform authenticate) latest release 2.1.0 but it fails at this point, there were some different options provided by google platform than given in your documentation. Can you please give an example with Google authentication?

I get many errors like:
context.idToken and oauthService.clientId is null, .toPromise(); is not a method.

this.oauthService.tryLogin({
validationHandler: context => {
        var search = new URLSearchParams();
        search.set('token', context.idToken); 
        search.set('client_id', oauthService.clientId);
        return http.get(validationUrl, { search}).toPromise();
    }
})

**Comment by manfredsteyer** [comment]
If you want to validate the id_token (which is necessary in hybrid apps but not in most web apps) you can use this hook. But the impl. of this hook is vendor specific. In my sample I've used a vender specific web api.
