### ISSUE TITLE
Real world examples

### ISSUE THREAD

**Issue by DDroll** [manfredsteyer/angular2-oauth2#21]
Can anybody provide an real-world example of using this lib? I tryed to authorize Steam using this, but maximum, that i achieved, was redirection after pressing "login" button on steamcomunity.com page without any sighn of authentification process. Is it possible? Steam using OpenId. Thanks!

**Comment by estemanp** [comment]
Hey, i have a example found. 

https://www.npmjs.com/package/angular2-oauth2

**Comment by denbezrukov** [comment]
@DDroll Hi, are you successful with this lib and steam?

**Comment by Vezuure** [comment]
@Dominionys 
@DDroll 
getLoginUrl(returnUrl?: string) {
    const realm = environment.loginRealm ? environment.loginRealm : location.origin;
    returnUrl = returnUrl || '' + this.router.createUrlTree(['/login']);
    return 'https://steamcommunity.com/openid/login?' + [
      'openid.ns=http://specs.openid.net/auth/2.0',
      'openid.mode=checkid_setup',
      'openid.return_to=' + realm + returnUrl,
      'openid.realm=' + realm,
      'openid.identity=http://specs.openid.net/auth/2.0/identifier_select',
      'openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select'].join('&');
  }
