### ISSUE TITLE
LocalStorage is not available on non-browser implementations

### ISSUE THREAD

**Issue by darbio** [manfredsteyer/angular2-oauth2#22]
I use server side pre-rendering in my app.

With this service, I have to turn this off in order to use it as the storage provider 'local storage' is not available in node.

This could be fixed by using a shim such as https://www.npmjs.com/package/node-localstorage

```
if (typeof localStorage === "undefined" || localStorage === null) {
  var LocalStorage = require('node-localstorage').LocalStorage;
  localStorage = new LocalStorage('./scratch');
}
```

**Comment by manfredsteyer** [comment]
Thx for this info. You can set a storage implementation of your choice (also an own) using setStorage(...)
