### ISSUE TITLE
Missing repository attribute in package.json

### ISSUE THREAD

**Issue by Soviut** [manfredsteyer/angular2-oauth2#5]
Without the repository attribute in package.json, NPM doesn't automatically know where to find the source. I realize that the source link is in the README but that doesn't show up in the NPM sidebar where users would normally look.

I could probably do a PR with this but can't do an npm publish.

**Comment by Soviut** [comment]
Created a PR here https://github.com/manfredsteyer/angular2-oauth2/pull/6

**Comment by manfredsteyer** [comment]
thx
