### ISSUE TITLE
The workaround to using SystemJS to load angular2-oauth2

### ISSUE THREAD

**Issue by TianCNCA** [manfredsteyer/angular2-oauth2#7]
I've been trying to use your module with [angular2-seed](https://github.com/mgechev/angular2-seed), and SystemJS keeps reporting errors regarding some weird path issues. It tries to look for the dependency modules under the top node_modules folder and somehow it wants to load node_modules/node_modules/package.json.

I spent a few hours on this and finally solved it by adding the following to my SystemJS config:

```
    packages: {
        rxjs: { defaultExtension: false },
        "angular2-oauth2": {
            //"baseURL": "/",
            //"format": "register",
            "defaultExtension": "js",
            "map": {
                "base64-js": "./node_modules/base64-js/lib/b64.js",
                "buffer": "./node_modules/buffer/index.js",
                "convert-hex": "./node_modules/sha256/node_modules/convert-hex/convert-hex.js",
                "convert-string": "./node_modules/sha256/node_modules/convert-string/convert-string.js",
                "ieee754": "./node_modules/buffer/node_modules/ieee754/index.js",
                "isarray": "./node_modules/buffer/node_modules/isarray/index.js",
                "js-base64": "./node_modules/js-base64/base64.js",
                "sha256": "./node_modules/sha256/lib/sha256.js"
            },
        }
    },
```

Not sure if this is the best approach, thought you might want to know this.

Thanks!

**Comment by jrezuke** [comment]
Thanks TianCNCA, this helped me.

**Comment by pofallon** [comment]
Yes, thanks, this helped me too!  In order to add this module to the Heroes tutorial app from the Angular site, I ended up with something similar (npm 3.10.6):

``` javascript
  var map = {
    'app':                        'app', // 'dist',

    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    'angular2-oauth2':            'node_modules/angular2-oauth2',
    'base64-js':                  'node_modules/base64-js/lib/b64.js',
    'buffer':                     'node_modules/buffer/index.js',
    'convert-hex':                'node_modules/convert-hex/convert-hex.js',
    'convert-string':             'node_modules/convert-string/convert-string.js',
    'ieee754':                    'node_modules/ieee754/index.js',
    'isarray':                    'node_modules/isarray/index.js',
    'js-base64':                  'node_modules/js-base64/base64.js',
    'sha256':                     'node_modules/sha256/lib/sha256.js'
  };

  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'angular2-oauth2':            { defaultExtension: 'js' }
  };
```

**Comment by comfroels** [comment]
This helped me a lot! thanks! I feel like this should probably be added to the README... 
I wonder if angular-cli can have some sort of wrapper for `npm install` that would handle all this systemjs boilerplate for you.

**Comment by FernandoFigueroa** [comment]
I have an angular-seed based project too, and this really helped me. I did: 
`npm install --save angular2-oauth2 base64-js buffer convert-hex convert-string ieee754 isarray js-base64 sha256`

In seed.config.ts file,  this is how my SYSTEM_CONFIG_DEV object looks now: 

``` js
  protected SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    packageConfigPaths: [
      `/node_modules/*/package.json`,
      `/node_modules/**/package.json`,
      `/node_modules/@angular/*/package.json`,
      `/node_modules/@angular2-material/*/package.json`
    ],
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      '@angular/common': `node_modules/@angular/common/bundles/common.umd.js`,
      '@angular/compiler': `node_modules/@angular/compiler/bundles/compiler.umd.js`,
      '@angular/core': `node_modules/@angular/core/bundles/core.umd.js`,
      '@angular/forms': `node_modules/@angular/forms/bundles/forms.umd.js`,
      '@angular/http': `node_modules/@angular/http/bundles/http.umd.js`,
      '@angular/platform-browser': `node_modules/@angular/platform-browser/bundles/platform-browser.umd.js`,
      '@angular/platform-browser-dynamic': `node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js`,
      '@angular/router': `node_modules/@angular/router/index.js`,
      'rxjs/*': `node_modules/rxjs/*`,
      'app/*': `/app/*`,
      '*': `node_modules/*`,
      'angular2-oauth2': 'node_modules/angular2-oauth2',
      'base64-js': 'node_modules/base64-js/lib/b64.js',
      'buffer': 'node_modules/buffer/index.js',
      'convert-hex': 'node_modules/convert-hex/convert-hex.js',
      'convert-string': 'node_modules/convert-string/convert-string.js',
      'ieee754': 'node_modules/ieee754/index.js',
      'isarray': 'node_modules/isarray/index.js',
      'js-base64': 'node_modules/js-base64/base64.js',
      'sha256': 'node_modules/sha256/lib/sha256.js'
    },
    packages: {
      rxjs: { defaultExtension: false },
      'angular2-oauth2': { defaultExtension: 'js' }
    }
  };
```

**Comment by Shakyamuni177te** [comment]
This is really helpful, but from what I've seen, the current version of node.js handles base64 calculations itself anyway. Unless there is some additional benefit to using this library over the one included in node isn't this solution adding bloat to the code? I'm not sure where the base64 handling function is called from in the node.js library, but I'm sure I wouldn't mind trying to find out and, if I find I am able, to rewrite this library to make the call from the internal node function, if people indicate they think this would be worthwhile.

**Comment by TianCNCA** [comment]
Note: I've switched to [oidc-client-js](https://github.com/IdentityModel/oidc-client-js). It's a more complete oidc/oauth library. It comes with typing definition files. It's written based on the es6 promise feature.

**Comment by bonaparte89** [comment]
I'm getting an error when I return from my identity server. 
Cannot read property decode of undefined.. --> TypeError: r.Base64 is undefined

http://localhost/#id_token=XXX&access_token=XXX&token_type=Bearer&expires_in=3600&scope=openid%20profile%20email%20browserapi&state=xxx&session_state=xxx

When I remove everything behind localhost I'm logged in. so token is set in local storage. 

I have all needed libarys loaded, no errors
any ideas?
