### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by davepar** [manfredsteyer/angular2-oauth2#9]
It would be cool if this supported refresh tokens. They're pretty handy when accessing Google APIs.

**Comment by WayneBarnard** [comment]
Anybody figured out how to do refresh tokens with this?

**Comment by saurabhbhatia** [comment]
In an ideal scenario, we cannot get refresh token for a javascript client side application. refer - https://tools.ietf.org/html/rfc6749#page-31 . It's not in OAuth specification. However, you can implement an oauth proxy server to get your refresh token. 

These guys have done the same 
https://github.com/MrSwitch/hello.js/blob/master/demos/google.html

**Comment by manfredsteyer** [comment]
Yes thats right. Refresh Tokens are not allowed for implicit flow. And the Code Flow - used in the sample above - is not allowed for Single Page Applications. Ofc you can do it, but then you are breaking the spec which may leed to security holes.

**Comment by manfredsteyer** [comment]
But you can redirect the user to the login page and when the user is still loged in there (by the means of a cookie), you will be redirected with a new token immediately.
